# Generated by Django 3.0.7 on 2024-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20240109_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
