# Generated by Django 3.0.7 on 2024-01-10 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articles_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=550, verbose_name='Keywords'),
            preserve_default=False,
        ),
    ]
