# Generated by Django 3.0.7 on 2024-01-10 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articles_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=550, verbose_name='File name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='job',
            field=models.CharField(max_length=550, verbose_name="Owner's job"),
        ),
    ]
