# Generated by Django 3.0.7 on 2024-01-10 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20240110_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
